version: "3.9"
services:
  testservice:
    build:
      context: .
      dockerfile: Dockerfile-service
    image: "sony-nre-testwork-testservice"
    ports:
      - "5000:5000"
  testrunner:
    build:
      context: .
      dockerfile: Dockerfile-testrunner
    image: "sony-nre-testwork-testrunner"
    links:
      - "testservice:service"
